### ISSUE TITLE
Failure to build v2.0.0

### ISSUE THREAD

**Issue by Rubber-Duck-999** [rust-psutil/rust-psutil#65]
Please provide any of the following information if relevant:

- rust-psutil version: v2.0.0
- target platform info
	- kernel version:
	- architecture: 64 bit
	- (if linux) distro: Ubuntu
- any relevant hardware info:

Cargo lists that the use of unstable library feature 'todo_macro'.

Not sure why this has occurred.

HouseGuard-SystemProcessor[https://github.com/Rubber-Duck-999/HouseGuard-SystemProcessor](url)

**Comment by Rubber-Duck-999** [comment]
Not sure if the package is stable, if so is I can revert the version

**Comment by cjbassi** [comment]
Oh, that's because you need to upgrade your rustc version to 1.39.

**Comment by Rubber-Duck-999** [comment]
Oh sorry I must have missed that

**Comment by cjbassi** [comment]
All good, I ran into the same issue initially to. :smile:
