### ISSUE TITLE
loadavg on MacOs

### ISSUE THREAD

**Issue by Martichou** [rust-psutil/rust-psutil#87]
As stated in [platform-support](https://github.com/rust-psutil/rust-psutil/blob/master/platform-support.md) rust-psutil does not currently implement loadavg on MacOs.

This is not a real issue as it's clear that this method is not yet implemented.
However I would like to work on bringing it to rust-psutil as part of a project I'm doing which need it.

Would it be interesting for you (this project) ? Also are you open to unsafe call to a C function ?

**Comment by cjbassi** [comment]
Yeah loadavg would be good to have. It's already implemented for linux. And unsafe calls are fine if necessary.

**Comment by Martichou** [comment]
Addressed in https://github.com/rust-psutil/rust-psutil/pull/89
