### ISSUE TITLE
Disk os module not accessible

### ISSUE THREAD

**Issue by WatakiWatako** [rust-psutil/rust-psutil#92]
Hey,

Currently it looks like it is not possible to import DiskIoCountersExt:

26 | use psutil::disk::os::linux::DiskIoCountersExt;
     |                   ^^ could not find `os` in `disk`

Adding "pub mod os;" at line 5 of src/disk/mod.rs resolves this issue:

https://github.com/rust-psutil/rust-psutil/blob/master/src/disk/mod.rs

Thank you!

**Comment by cjbassi** [comment]
Fixed on master, thanks for pointing it out.
